OT166-46 Endpoint Creación Novedades
alkemyTech/OT166-Java-server pull request #23
Opened 2022-03-24 19:55 UTC by KaykiPrex

# [OT166-46#](https://alkemy-labs.atlassian.net/browse/{OT166-46#})

-Endpoint for creation News
-Creation News service
-Creation mapper for news
-Creation DTO for request and response

### HOW HAS THIS BEEN TESTED?

Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration.

- [x] Postman.
- [ ] Unit test.
- [ ] Integration test.
- [ ] No testing required (only applies for tech task).

**Test Configuration**:

* ...
* ...

**Screenshots**:

* ....

### CHECKLIST

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

- [ ] I have added the new resource in the Postman Collection file.
![Postman_News_Response](https://user-images.githubusercontent.com/56768010/159998410-430f647a-3dc0-4ee4-9ac9-d163aa38748c.jpg)
![Postman_News_ErrorEmpty](https://user-images.githubusercontent.com/56768010/159998586-4481a53e-6333-49a4-afdc-881f43197412.jpg)
![Postman_News_InvalidData](https://user-images.githubusercontent.com/56768010/159998628-fc811574-ac52-4d40-b3e1-2d3f8dc6af31.jpg)

2022-03-25 00:57 UTC, mkain0 requested changes

2022-03-25 00:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/abstraction/INewsService.java
> +  NewsResponse createNews(NewsRequest newsRequest);
@KaykiPrex Creo que justo te tuviste que ir, pero esto del createNews vs create lo conversamos en el video que grabo @MatiasEsp404 respecto a algunos tips rápidos para ir aplicando buenas prácticas + SOLID.

2022-03-25 00:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/abstraction/INewsService.java
> +public interface INewsService {
SOLID: ICreateNewsService

Conversado en otros PRs.

2022-03-25 00:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/rest/request/NewsRequest.java
> +public class NewsRequest {
Mi recomendación para evitar complicaciones con Swagger es que creen un request DTO por operación. En este caso se debería llamar CreateNewsRequest.

2022-03-25 00:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/rest/request/NewsRequest.java
> +  @NotEmpty(message = "image may not be empty")
MINOR: "The image must not be empty."

2022-03-25 00:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/rest/request/NewsRequest.java
> +  @Pattern(regexp = "[0-9]+", message = "image must contain numbers")
Este pattern no condice con lo solicitado en el ticket. Debería ser: ^[a-zA-Z0-9_]*$

El mensaje debería ser: "The image has invalid format." o "The image accepts only alphanumeric characters."

2022-03-25 00:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/rest/request/NewsRequest.java
> +  @NotEmpty(message = "text may not be empty")
MINOR: "The text must not be empty."

2022-03-25 00:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/rest/request/NewsRequest.java
> +  @NotEmpty(message = "name may not be empty")
MINOR: "The name must not be empty."

2022-03-25 00:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/rest/request/NewsRequest.java
> +  @Pattern(regexp = "[a-zA-Z0-9\\s]+", message = "text must contain letters and numbers")
Esta expresión regular no me estaría funcionando. Creo que lo correcto seria: ^[a-zA-Z_ ]*$

Adicionalmente, el mensaje debería ser: "The text has invalid format." o "The text accepts only alphanumeric characters and blank spaces."

FYI: testeado en https://regex101.com/

2022-03-25 00:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/rest/request/NewsRequest.java
> +  @Pattern(regexp = "[a-zA-Z\\s]+", message = "name must contain letters and blank spaces")
Esta expresión regular no me estaría funcionando. Puede que lo correcto sea: ^[a-zA-Z_ ]*$

FYI: testeado en https://regex101.com/

2022-03-25 00:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/rest/request/NewsRequest.java
> +  @Size(max = 50)
Falta el mensaje en caso de que no pase la validación.

2022-03-25 00:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/rest/resource/NewsResource.java
> +  INewsService newsService;
MINOR: debería ser private.

2022-03-25 00:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/rest/resource/NewsResource.java
> +  INewsService newsService;
También mismo comentario que en https://github.com/alkemyTech/OT166-Java-server/pull/21#discussion_r834108182

2022-03-25 00:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/rest/resource/NewsResource.java
> +  @PostMapping(produces = MediaType.APPLICATION_JSON_VALUE)
Falta definir el producer.

2022-03-25 00:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/rest/resource/NewsResource.java
> +    URI location = new URI(URI_NEWS + newsResponse.getId());
REST dice que se debe devolver la URL apuntando al recurso creado, pero esta no es la forma correcta de hacerlo porque cuando esto esta deployado en un servidor la URL no tiene el formato que esta definido en la constante. Opciones, realizarlo de la forma apropiada o quitarlo del scope del PR.

2022-03-25 00:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/rest/resource/NewsResource.java
> +  private static final String URI_NEWS = "http://localhost:8080/news/";
Esta no es la forma correcta de popular la url de un servicio. Por favor, ver mi comentario en el método del resource.

2022-03-25 00:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/NewsService.java
> +      categoryRepository.save(category);
No es parte del scope del ticket crear la categoría. Como se menciona en las tech notes, este registro ya debe existir en la base de datos.

2022-03-25 00:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/NewsService.java
> +    NewsEntity newsEntity = newsMapper.toNewsEntity(newsRequest);
Falta setear el softDelete en false.

2022-03-25 00:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/NewsService.java
> +    NewsResponse newsResponse = newsMapper.toNewsResponse(newsRepository.save(newsEntity));
CLEAN CODE: no es necesario crear la variable newsResponse, se puede realizar directamente el return:

return newsMapper.toNewsResponse(newsRepository.save(newsEntity));

2022-03-25 00:58 UTC, mkain0 commented
@KaykiPrex MISSING REQUIREMENT: faltan setear que roles tienen acceso a este endpoint.

2022-03-25 02:24 UTC, MatiasEsp404 commented on src/main/java/com/alkemy/ong/application/service/abstraction/INewsService.java
> +  NewsResponse createNews(NewsRequest newsRequest);
Si no me equivoco, Maga había dicho que el nombre de la entidad era redundante en el método. O sea, createNews debería llamarse simplemente create.

2022-03-27 17:18 UTC, mkain0 approved these changes

2022-03-27 17:18 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/rest/request/CreateNewsRequest.java
> +  @Pattern(regexp = RegExpressionUtils.ALPHABETIC_CHARACTERS_WITH_BLACK_SPACES,
xD deje un typo en las contantes. Luego lo corrijo!

2022-03-27 17:18 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/rest/request/CreateNewsRequest.java
> +  @Size(max = 50, message = "Maximum size is 50 characters.")
En esta validación falta incorporar el nombre del atributo que no cumple la validación.

2022-03-27 17:18 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/rest/resource/NewsResource.java
> +        .toUri();
Claps!

2022-03-27 17:18 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/NewsService.java
> +    }
CLEAN CODE: si se invierte la condición, se mejora la identación del código.

2022-03-27 17:20 UTC, mkain0 approved these changes

2022-03-27 17:20 UTC, merged