Ot166 78 - Endpoint Eliminación Comentarios
alkemyTech/OT166-Java-server pull request #35
Opened 2022-03-28 15:33 UTC by adrianlunau

# [Ticket OT166-78#](https://alkemy-labs.atlassian.net/browse/{OT166-78})

Please include a summary of the change and which issue is fixed. Please also include relevant
motivation and context. List any dependencies that are required for this change.

### HOW HAS THIS BEEN TESTED?

Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration.

- [x] Postman.
- [ ] Unit test.
- [ ] Integration test.
- [ ] No testing required (only applies for tech task).

**Test Configuration**:

* ...
* ...

**Screenshots**:
USER intenta borrar un comentario inexistente
![USER intenta borrar un comentario inexistente](https://user-images.githubusercontent.com/85313722/160433796-c5c9cc7e-f14b-47c0-b2e3-20e14175bf55.PNG)

USER intenta borrar un comentario no propio
![USER intenta borrar comentario no propio](https://user-images.githubusercontent.com/85313722/160433883-bc28fbef-6886-445f-8aa9-0efe31c9578b.PNG)

USER borra comentario propio
![USER borra comentario propio](https://user-images.githubusercontent.com/85313722/160433939-bd751fcf-4254-4098-b7d4-02c05f5e6535.PNG)

ADMIN borra comentario de un USER
![ADMIN borra comentario de un USER](https://user-images.githubusercontent.com/85313722/160434000-858c0008-c9b5-4363-8ec7-a400164b984a.PNG)

* ....

### CHECKLIST

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [x] I have added the new resource in the Postman Collection file.

2022-03-28 18:12 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/CommentService.java
> +  }
CLEAN CODE: los if-else siempre son sucios. Si se puede mejorar la identación, se mejora la lectura del código y por ende la calidad del mismo:

```
if (!securityContextHolderUtils.hasAdminRole()
        && !commentEntity.getUser().getId().equals(userAuthenticated.getId())) {
      throw new OperationNotPermitedException("No permission to delete this comment.");
    }

    commentRepository.delete(commentEntity);
```

2022-03-28 18:17 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/CommentService.java
> +    if (idUserComment.equals(userAuthenticated.getId())
Por qué comparar los ID si son objetos del mismo tipo? Por favor, utilizar equals y sobreescribir el método en la entity.

2022-03-28 18:17 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/UserService.java
> +  public UserEntity getUser(String username) {
Este método no debe cambiar su modificador de acceso. Motivos explicados en el Security util.

2022-03-29 13:24 UTC, adrianlunau commented
Para poder hacer pull y pedir re-review tuve que modificar las dependencias de AWS. No entiendo mucho del tema, pero aparentemente así como estaban windows no podía enumerar todos los subproyectos que traía esa dependencia por que superaba el limite de la longitud máxima del path.

2022-03-29 16:16 UTC, mkain0 requested changes
@adrianlunau Revisa mis comentarios y hace un pull antes de realizar las modificaciones porque hice dos cambios mientras lo estaba revisando. Gracias!

2022-03-29 16:16 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/util/SecurityUtils.java
> +            .equals(Role.ADMIN.getFullRoleName()));
EL NPE exception no va a ocurrir porque es un MUST que user tenga un authority. Sin embargo, en otro contexto esto puede tirar un NPE.

Mencionado en:
https://github.com/alkemyTech/OT166-Java-server/pull/35#discussion_r836699274

2022-03-29 16:16 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/CommentService.java
> +    String userAuthenticated = securityUtils.getUserAuthenticated();
getUserAuthenticated() debería devolver el user que esta autenticado, una instancia de UserEntity. Aplicando lo que se converso en https://github.com/alkemyTech/OT166-Java-server/pull/35#discussion_r836681286

2022-03-29 16:16 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/CommentService.java
> +        && !commentEntity.getUser().getEmail().equals(userAuthenticated)) {
Por favor, realizar lo solicitado en https://github.com/alkemyTech/OT166-Java-server/pull/35#discussion_r836717544

2022-03-29 19:17 UTC, mkain0 requested changes

2022-03-29 19:17 UTC, mkain0 commented on src/main/resources/application.properties
> +spring.datasource.password=America189
Por favor, revertir este cambio.

2022-03-29 19:17 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/util/SecurityUtils.java
> +  }
El método que tenias anteriormente estaba correcto: 
```
  public boolean hasAdminRole() {
    return getAuthentication().getAuthorities().stream()
        .anyMatch(grantedAuthority -> Role.ADMIN.getFullRoleName()
            .equals(grantedAuthority.getAuthority()));
  }
```

2022-03-29 19:17 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/CommentService.java
> +        && !commentEntity.getUser().getEmail().equals(userAuthenticated.getUsername())) {
Como conversamos en la planning, hacer uso de POO. Comparar los objetos y sobreescribir el equals.

2022-03-29 21:24 UTC, mkain0 approved these changes

2022-03-29 21:25 UTC, merged