OT166-66: Endpoint Actualización Testimonios
alkemyTech/OT166-Java-server pull request #70
Opened 2022-04-08 01:22 UTC by celesdv

# OT166-66 https://alkemy-labs.atlassian.net/browse/OT166-66

Criterios de aceptación

PUT /testimonials/:id - Deberá validar que la novedad exista en base al id enviado por parámetro. En el caso de que no exista, deberá devolver un error: “Testimonial not found.“, mientras que en caso contrario, deberá actualizarla y devolverla con los datos nuevos.

Deberá validar los siguientes campos:

name: caracteres alfabéticos con espacios y no mas de 50 caracteres.

content: caracteres alfanuméricos con espacios. No más de 150 caracteres.

image: no tiene validaciones.

Todos los campos son opcionales.

### HOW HAS THIS BEEN TESTED?

Please describe the tests that you ran to verify your changes. Provide instructions so we can
reproduce. Please also list any relevant details for your test configuration.

- [x] Postman.
- [ ] Unit test.
- [ ] Integration test.
- [ ] No testing required (only applies for tech task).

**Test Configuration**:

* ...
* ...

**Screenshots**:
![TestimonialBadRequest1](https://user-images.githubusercontent.com/66212987/162344672-892e8271-5296-4294-af4f-1716dcd7ba2a.png)
![TestimonialBadRequest2](https://user-images.githubusercontent.com/66212987/162344680-642b6217-ec99-4c57-b435-9d110d3009aa.png)
![TestimonialNotFound](https://user-images.githubusercontent.com/66212987/162344682-b9b40465-6361-463b-ac92-d108383f1546.png)
![TestimonialPut](https://user-images.githubusercontent.com/66212987/162344683-969371d2-77f9-4395-9b1e-01ec33d1dbc7.png)

### CHECKLIST

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [x] I have added the new resource in the Postman Collection file.

2022-04-08 08:27 UTC, mkain0 requested changes

2022-04-08 08:27 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/rest/request/UpdateTestimonialRequest.java
> +public class UpdateTestimonialRequest {
Como menciona el ticket, todos los campos son opcionales. Algunas de estas annotations no permiten que el campo sea null, por favor, corregir el código.

2022-04-08 19:02 UTC, celesdv reviewed
En TestimonialEntity el name es NotNull, asique realice la verificacion para cumplir con esto sino no me permitia la actualizacion.

2022-04-11 08:24 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/rest/request/UpdateTestimonialRequest.java
> +  @Pattern(regexp = RegExpressionUtils.ALPHANUMERIC_CHARACTERS_WITH_BLANK_SPACES,
Esta perfecto. Estan fuera de nuestro scope los signos de puntuación. Esto lo charlamos con Mati a comienzo de la aceleración.

2022-04-11 08:26 UTC, mkain0 approved these changes

2022-04-11 08:26 UTC, merged