OT166-57 Endpoint Creación Slides
alkemyTech/OT166-Java-server pull request #71
Opened 2022-04-08 05:45 UTC by MatiasEsp404

# [OT166-57 Endpoint Creación Slides](https://alkemy-labs.atlassian.net/browse/OT166-57)

### Criterios de aceptación

- Se debe hacer una peticion POST /slides 
- Recibirá la imágen a almacenar en base 64. La misma deberá ser decodeada y almacenada en Amazon S3. 
- En el caso de no recibir el campo order, deberá establecer el mismo como el último en base a los existentes.
- Devuelve los datos del slide en la response.

### HOW HAS THIS BEEN TESTED?

- [x] Postman.
- [ ] Unit test.
- [ ] Integration test.
- [ ] No testing required (only applies for tech task).

### Screenshots:

#### Con order: 
![image](https://user-images.githubusercontent.com/88750230/162371854-4fb7e417-0b42-482f-ae91-937f7b9f1a77.png)

#### Sin order:
![image](https://user-images.githubusercontent.com/88750230/162371958-1569e443-f6f9-4122-b9e7-97389198e54b.png)

#### Imagen subida en amazon: 
https://cohorte-marzo-77238c6a.s3.amazonaws.com/Pikachu%20Detective

### CHECKLIST

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added the new resource in the Postman Collection file.

2022-04-08 08:57 UTC, mkain0 requested changes

2022-04-08 08:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/rest/response/SlideResponse.java
> +  private Long id;
El ID no debe ser parte de las request en las que actualmente se incorporan las Slides, por ejemplo el get organization details. Por lo tanto, modificar el mapper y agregar las anotaciones correspondientes a esta clase pra cumplir con esos requisitos.

2022-04-08 08:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/SlideService.java
> +        .inputStream(stream)
En vez de recibir un stream, debería recibir un String (slideRequest.getEndcodedImage()) y como parte del proceso de construcción utilizar el decodeImage método para convertirla en un InputStream. De esta forma, le delegamos la responsabilidad al ImageImp completamente, ya que en definitiva es el quien sabe como desencodearla basandonos en la línea 65.

2022-04-08 08:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/SlideService.java
> +        ImageImp.decodeImage(slideRequest.getEncodedImage()));
Todo esto debería ser responsabilidad de ImageImp. 
Ver comentario en línea 73 para más detalles.

2022-04-08 08:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/SlideService.java
> +    return uploadImageDelegate.upload(imageBuilder(slideRequest, inputStream));
Acá tenes un claro code smell, le pasas el slideRequest y el inputStream, pero el inputStream se crea en base a data que tiene el slideRequest.

2022-04-08 08:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/util/image/ImageImp.java
> +  private InputStream inputStream;
Estos atributos deberían ser inmutables.

2022-04-08 08:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/util/image/ImageImp.java
> +  public static byte[] decodeImage(String encodedImage) {
Este método debería ser privado por los comentarios mencionados en el service y en ese caso no hace falta que sea static.

2022-04-08 08:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/util/image/ImageImp.java
> +public final class ImageImp implements IImage {
MINOR: No me gusta utilizar la palabra Imp en las clases porque siempre que una clase concreta implemente una interfaz, es una implementación en si misma. Podríamos renombrar la clase a Image directamente.

Por otro lado, el final en la definición de la clase no la hace inmutable, solamente no permite que otras clases extiendan de ella. En este caso, no sería un problema que otras extiendan de esta clase. OJO con el uso de final, porque dependiendo donde se utilice, tiene comportamientos diferentes.

2022-04-08 08:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/SlideService.java
> +    return (order == null) ? slideRepository.getHighestOrder() + 1 : order;
order es un Integer, por lo tanto también hay que verificar que no sea 0.

2022-04-08 08:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/database/repository/ISlideRepository.java
> +  @Query(value = "SELECT MAX(s.order) FROM SlideEntity s")
Probaste que pasa si no hay slides en la base de datos?

2022-04-10 23:41 UTC, MatiasEsp404 commented on src/main/java/com/alkemy/ong/application/service/SlideService.java
> +    return (order == null) ? slideRepository.getHighestOrder() + 1 : order;
Hola Maga! Lo voy a hacer como vos me digas que lo haga pero ¿qué problema hay si es cero? 🤔

2022-04-10 23:47 UTC, MatiasEsp404 commented on src/main/java/com/alkemy/ong/application/service/SlideService.java
> +    return (order == null) ? slideRepository.getHighestOrder() + 1 : order;
O sea, ¿lo que me estás queriendo decir es que order tiene que ser entero (exceptuando el cero)? 🤔 🤔 🤔

2022-04-10 23:51 UTC, MatiasEsp404 commented on src/main/java/com/alkemy/ong/infrastructure/database/repository/ISlideRepository.java
> +  @Query(value = "SELECT MAX(s.order) FROM SlideEntity s")
Jaja! Que tonto, no lo había notado 😞 
![image](https://user-images.githubusercontent.com/88750230/162645242-e55d3393-4a7d-45c6-8f34-ad413d299e55.png)

2022-04-11 10:46 UTC, mkain0 commented
@MatiasEsp404 fijate que con los merge de esta mañana se generaron conflictos. Para que lo tengas en cuenta antes de solicitar review nuevamente. Gracias!

2022-04-11 19:09 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/util/image/Image.java
> +    return new ByteArrayInputStream(Base64.getDecoder().decode(encodedImage));
JUST FOR FUTURE REFERENCE: recientemente agregamos Apache Commons al proyecto, así que también se podrían haber utilizado Base64#decodeBase64

2022-04-11 19:13 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/SlideService.java
> +    return (order == null || order == 0) ? slideRepository.getHighestOrder() + 1 : order;
:P por lo conversado en la daily de hoy, mi sugerencia tiene un bug y debería ser <= 0.

2022-04-11 19:13 UTC, mkain0 approved these changes

2022-04-11 19:14 UTC, merged