OT166-79: Endpoint to list Comments based on a news
alkemyTech/OT166-Java-server pull request #79
Opened 2022-04-12 04:09 UTC by MatiasEsp404

# [OT166-79: Endpoint to list Comments based on a news](https://alkemy-labs.atlassian.net/browse/OT166-79)

### Criterios de aceptación

- **GET** /news/:id/comments - Devolverá todos los comments pertenecientes a una news

### HOW HAS THIS BEEN TESTED?

- [x] Postman.
- [ ] Unit test.
- [ ] Integration test.
- [ ] No testing required (only applies for tech task).

### Screenshots:

![image](https://user-images.githubusercontent.com/88750230/162878463-07369045-a963-4e45-bee0-fb1b7f401f83.png)

### CHECKLIST

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added the new resource in the Postman Collection file.

2022-04-12 10:42 UTC, mkain0 requested changes

2022-04-12 10:42 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/abstraction/IGetCommentService.java
> +public interface IGetCommentService {
Creo que este método iría mejor en IGetNewsService

2022-04-12 10:42 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/CommentService.java
> +      String newsName, List<CommentEntity> commentsList) {
AVOID IMPLEMENTATIONS IN THE NAMES: commentEntities

2022-04-12 10:42 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/CommentService.java
> +    List<CommentEntity> commentsList = commentRepository.findByNewsId(id);
AVOID IMPLEMENTATIONS IN THE NAMES: commentEntities

2022-04-12 10:42 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/CommentService.java
> +    List<CommentEntity> commentsList = commentRepository.findByNewsId(id);
MINOR a este punto del aprendizaje. Estas dos request a la BD se pueden combinar en una sola utilizando Tuples.

2022-04-12 18:23 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/abstraction/IGetCommentService.java
> +public interface IGetCommentService {
Resuelto en daily.

2022-04-13 01:22 UTC, MatiasEsp404 commented on src/main/java/com/alkemy/ong/application/service/abstraction/IGetCommentService.java
> +public interface IGetCommentService {
Al final lo pasé a IGetNewsService porque con los cambios que hice ya no estoy reutilizando métodos.

2022-04-13 01:35 UTC, MatiasEsp404 commented on src/main/java/com/alkemy/ong/application/service/CommentService.java
> +    List<CommentEntity> commentsList = commentRepository.findByNewsId(id);
Rehice todo el código y ahora solo hago una consulta en la base de datos 😄👍🏼 

No pude usar Tuples (Pair) porque no me lo agarraba el repositorio así que usé Maps 😥 Te comenté este problema mas en detalle por Slack.

En fin, el código está funcionado aunque no sé si me gusta mas antes o ahora 😅 En un ratito hago el PR.

![codigo funcionando con querys](https://user-images.githubusercontent.com/88750230/163080953-de32db27-2f5a-43b1-bea4-bb4aa5ceec83.png)

2022-04-13 08:47 UTC, mkain0 commented on src/main/java/com/alkemy/ong/infrastructure/database/mapper/abstraction/ICommentMapper.java
> +import org.mapstruct.Named;
No hay que trabajar a altas horas porque se va dejando código sucio :)

2022-04-13 09:13 UTC, mkain0 requested changes

2022-04-13 09:13 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/NewsService.java
> +    existNewsById(id);
Esto no debería ser requerido porque el mapa va a estar vacío si la news no existe.

2022-04-13 09:13 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/NewsService.java
> +        .name(queryResponses.get(0).get("newsName").toString())
El schema de la base de datos dice que el name de una news no puede ser null, pero tene en cuenta que en otro contexto esto puede producir un NPE. Siempre hay que tratar de evitar los posibles NPE.

2022-04-13 09:13 UTC, mkain0 commented on src/main/java/com/alkemy/ong/application/service/NewsService.java
> +  }
En este caso utilizaste un mapa y no tuplas, entonces queda desdibujado donde estaría la responsabilidad de este mapeo. SIn embargo, cuando trabajamos con Tuple sabemos que esa clase es parte de JPA y no debe salir del contexto del repository porque si te pones a pensar, el servicio no tiene porque conocer cuales son los nombres de cada una de las columnas incluidas en la query, es el repository quien debe entregar un DTO que le permita conocer claramente cual es la data obtenida después de realizar la query.

2022-04-13 09:36 UTC, mkain0 commented
@MatiasEsp404 Fijate que cuando lo estaba revisando hice algunos de los cambios que marque como "Resolved". Lo del mapa no hace falta que lo cambies, pero te dejo acá algunos ejemplos de como funciona Tuple:
https://www.logicbig.com/tutorials/java-ee-tutorial/jpa/criteria-api-tuple.html

En buenas prácticas se trata de evitar escribir:

- query native: no se hace uso de las ventajas de un ORM y si se decide cambiar de BD es un big problem.
- JPLQ/HQL: si se renombrar atributos de una entidad, puede llegar a producción con un bug rápidamente si durante el proceso manual de buscar ese String en el código y renombrarlo se olvida de alguno.

Mergeo el PR y si queres realizar alguna modificación extra o encuentras algún error feel free to open another PR. 

Gracias!

2022-04-13 09:38 UTC, mkain0 approved these changes

2022-04-13 09:39 UTC, merged